website/auth.py
from flask import render_template, redirect, url_for, flash, Blueprint
from flask_wtf import FlaskForm
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo
from .models import User
from . import db
from . import current_year

auth = Blueprint('auth', __name__)


class LogForm(FlaskForm):
    email = StringField(label='Email', validators=[DataRequired(), Email()])
    password = PasswordField(label='Password', validators=[DataRequired(), Length(min=8)])
    submit = SubmitField(label='Log In')


class SignUpForm(FlaskForm):
    name = StringField(label="Username", validators=[DataRequired()])
    email = StringField(label='Email', validators=[DataRequired(), Email()])
    password = PasswordField(label='Password', validators=[DataRequired(), Length(min=8)])
    confirm_pass = PasswordField(label="Confirm password", validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField(label='Sign Up')


@auth.route("/login", methods=['GET', 'POST'])
def login():
    login_form = LogForm()
    # If user submits data at this route.
    if login_form.validate_on_submit():
        mail = login_form.email.data
        password = login_form.password.data
        user = User.query.filter_by(mail=mail).first()
        if not user or not check_password_hash(pwhash=user.password, password=password):
            flash(message='Wrong email or password!')
            return render_template('login.html', year=current_year, form=login_form)
        else:
            flash(message='Login successful!')
            login_user(user=user)
        return redirect(url_for('views.home'))

    # If user requests the route.
    return render_template('login.html', year=current_year, form=login_form)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    sign_up_form = SignUpForm()
    # If user submits data at this route.
    if sign_up_form.validate_on_submit():
        mail = sign_up_form.email.data
        name = sign_up_form.name.data
        password = sign_up_form.password.data
        # Check if user exists
        user = User.query.filter_by(username=name).first()
        user_mail = User.query.filter_by(mail=mail).first()
        if user or user_mail:
            flash(message='Username or Email already in-use!')
            return render_template('sign_up.html', year=current_year, form=sign_up_form)
        else:
            hash_and_salt_pass = generate_password_hash(password=password, method='pbkdf2:sha256', salt_length=8)
            new_user = User(username=sign_up_form.name.data, mail=sign_up_form.email.data, password=hash_and_salt_pass)
            db.session.add(new_user)
            db.session.commit()

            return redirect(url_for('views.home'))

    # If user requests the route.
    return render_template('sign_up.html', year=current_year, form=sign_up_form)

website/views.py
from flask import render_template, redirect, url_for, Blueprint, abort, json, jsonify
import smtplib
from flask_wtf import FlaskForm
from flask_login import login_required, current_user
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Email, InputRequired
from .models import Post
from . import db
from . import current_year
from functools import wraps
import random

views = Blueprint('views', __name__)


def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        # If id is not 1 then return abort with 403 error
        if current_user.id != 1:
            return abort(403)
        # Otherwise continue with the route function
        return f(*args, **kwargs)

    return decorated_function


class BlogForm(FlaskForm):
    title = StringField(label='Title', validators=[InputRequired()])
    subtitle = StringField(label='Subtitle', validators=[InputRequired()])
    body = TextAreaField(label='Body', validators=[InputRequired()])
    difficulty = SelectField(label='Difficulty', choices=["🥾", "🥾🥾", "🥾🥾🥾", "🥾🥾🥾🥾", "🥾🥾🥾🥾🥾"])
    length = SelectField(label='Duration', choices=["⌛", "⌛⌛", "⌛⌛⌛", "⌛⌛⌛⌛", "⌛⌛⌛⌛⌛"])
    submit = SubmitField(label='Submit', validators=[InputRequired()])


class ContactForm(FlaskForm):
    name = StringField(label="Name", validators=[InputRequired()])
    email = StringField(label='Email', validators=[DataRequired(), Email()])
    message = TextAreaField(label="Message", validators=[InputRequired()])
    submit = SubmitField(label='Send')


@views.route('/')
def home():
    all_posts = Post.query.all()
    return render_template("index.html", year=current_year, posts=all_posts)


@views.route("/blog/<int:index>")
def get_blog(index):
    requested_post = Post.query.get(index)
    return render_template("post.html", year=current_year, post=requested_post)


@views.route("/contact_me", methods=['GET', 'POST'])
def contact_me():
    contact_form = ContactForm()
    # If user submits data at this route.
    if contact_form.validate_on_submit():
        # send_email(contact_form.name, contact_form.email, contact_form.message)
        return render_template('contact_form.html', year=current_year, form=contact_form, msgsent=True)
    # If user requests the route.
    return render_template('contact_form.html', year=current_year, form=contact_form, msgsent=False)


def send_email(name, email, message):
    email_message = f"Subject:New Message\n\nName: {name}\nEmail: {email}\nMessage:{message}"
    with smtplib.SMTP("smtp.gmail.com") as connection:
        connection.starttls()
        connection.login(USER_MAIL, MAIL_PASSWORD)
        connection.sendmail(USER_MAIL, USER_MAIL, email_message)


@views.route("/add", methods=['GET', 'POST'])
@login_required
@admin_only
def add_blog():
    blog = BlogForm()
    # If user submits data at this route.
    if blog.validate_on_submit():
        new_post = Post(title=blog.title.data, subtitle=blog.subtitle.data, body=blog.body.data,
                        difficulty=blog.difficulty.data, length=blog.length.data)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('views.home'))
    # If user requests the route.
    return render_template('add.html', year=current_year, blog=blog)


@views.route("/edit/<int:index>", methods=['GET', 'POST'])
@login_required
@admin_only
def edit_blog(index):
    requested_post = None
    all_posts = Post.query.all()
    for post in all_posts:
        if post.id == index:
            requested_post = post
    blog = BlogForm(obj=requested_post)
    # If user submits data at this route.
    if blog.validate_on_submit():
        edited_post = Post.query.get(index)
        edited_post.title = blog.title.data
        edited_post.subtitle = blog.subtitle.data
        edited_post.body = blog.body.data
        edited_post.difficulty = blog.difficulty.data
        edited_post.length = blog.length.data
        db.session.commit()
        return redirect(url_for('views.home'))
    # If user requests the route.
    return render_template('edit.html', year=current_year, blog=blog, index=requested_post.id)


@views.route("/delete/<int:index>")
@login_required
@admin_only
def delete_blog(index):
    post_to_delete = Post.query.get(index)
    db.session.delete(post_to_delete)
    db.session.commit()
    return redirect(url_for('views.home'))


# API call routes
@views.route('/random')
def get_random_hike():
    all_hikes = Post.query.all()
    random_hike = random.choice(all_hikes).to_dict()
    return jsonify(random_hike)


@views.route('/all')
def get_all_hikes():
    all_hikes = Post.query.all()
    all_hikes_dict = {"hikes": [hike.to_dict() for hike in all_hikes]}
    return jsonify(all_hikes_dict)

website/templates/add.html
{% extends "base.html" %}
{% block content %}
    <div class="top">
        <div class="title"><h1>Add new blog</h1></div>
    </div>
    <div class="card">
    <form method="POST" action="{{ url_for('views.add_blog') }}" novalidate >
        {{ blog.csrf_token }}
        <p>
            {{ blog.title.label }} {{ blog.title(size=1) }}
            {% for err in blog.title.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.subtitle.label }} {{ blog.subtitle(size=20) }}
            {% for err in blog.subtitle.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.body.label }} {{ blog.body(size=20) }}
            {% for err in blog.body.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.difficulty.label }} {{ blog.difficulty(size=1) }}
            {% for err in blog.difficulty.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.length.label }} {{ blog.length(size=1) }}
            {% for err in blog.length.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        {{ blog.submit }}
    </form>
    </div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My hiking blog</title>
    <link href="https://fonts.googleapis.com/css2?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/styles.css">
</head>
<body>
<div class="wrapper">
    <div class="dropdown">
        <button class="dropbtn">Menu</button>
        <div class="dropdown-content">
            <a href="{{ url_for('views.home') }}">Home</a>

            {% if not current_user.is_authenticated %}
            <a href="{{ url_for('auth.login') }}">Log In</a>
            <a href="{{ url_for('auth.sign_up') }}">Sign Up!</a>
            <a href="{{ url_for('views.contact_me') }}">Contact me!</a>
            {% endif %}
            {% if current_user.is_authenticated %}
            {% if current_user.id == 1 %}
            <a href="{{ url_for('views.add_blog') }}">Add new post</a>
            {% endif %}
            <a href="{{ url_for('views.contact_me') }}">Contact me!</a>
            <a href="{{ url_for('auth.logout') }}">Logout</a>
            {% endif %}
            <div id="profdiv">Profile
                <p id="prof">Current user:
                        {% if not current_user.is_authenticated %}
                        None
                        {% else %}
                        {{current_user.username}}
                        {% endif %}
                </p>
            </div>
        </div>
    </div>
{% block content %}
{% endblock %}
</div>
</body>
<footer>
    <p>Copyright {{year}}. Made by Ognyan Petkov.</p>
</footer>
</html>

website/templates/contact_form.html
{% extends "base.html" %}
{% block content %}
{% if msgsent %}
<div class="card">
    <h1>Your message was sent successfully!</h1>
    <a href="/">Go back!</a>
</div>
{% else %}
<div class="wrapper">
    <div class="top">
        <div class="title"><h1>Contact form</h1></div>
    </div>
</div>
<div class="wrapper">
    <div class="dropdown">
        <button class="dropbtn">Menu</button>
        <div class="dropdown-content">
            <a href="{{ url_for('views.home') }}">Home</a>
            {% if not current_user.is_authenticated %}
            <a href="{{ url_for('auth.login') }}">Log In</a>
            <a href="{{ url_for('auth.sign_up') }}">Sign Up!</a>
            <a href="{{ url_for('views.contact_me') }}">Contact me!</a>
            {% endif %}
            {% if current_user.is_authenticated %}
            {% if current_user.id == 1 %}
            <a href="{{ url_for('views.add_blog') }}">Add new post</a>
            {% endif %}
            <a href="{{ url_for('views.contact_me') }}">Contact me!</a>
            <a href="{{ url_for('auth.logout') }}">Logout</a>
            {% endif %}
        </div>
    </div>

    <div class="card">
    <form method="POST" action="{{ url_for('views.contact_me') }}" novalidate >
        {{ form.csrf_token }}
        <p>
            {{ form.name.label }} {{ form.name(size=20) }}
            {% for err in form.name.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }} {{ form.email(size=20) }}
            {% for err in form.email.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.message.label }} {{ form.message(size=20) }}
            {% for err in form.message.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        {{ form.submit }}
    </form>
    </div>
</div>
{% endif %}
{% endblock %}

website/templates/edit.html
{% extends "base.html" %}
{% block content %}
    <div class="top">
        <div class="title"><h1>Edit blog</h1></div>
    </div>
    <div class="card">
    <form method="POST" action="{{ url_for('views.edit_blog', index=index) }}" novalidate >
        {{ blog.csrf_token }}
        <p>
            {{ blog.title.label }} {{ blog.title(size=1) }}
            {% for err in blog.title.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.subtitle.label }} {{ blog.subtitle(size=20) }}
            {% for err in blog.subtitle.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.body.label }} {{ blog.body(size=20) }}
            {% for err in blog.body.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.difficulty.label }} {{ blog.difficulty(size=1) }}
            {% for err in blog.difficulty.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>
            {{ blog.length.label }} {{ blog.length(size=1) }}
            {% for err in blog.length.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        {{ blog.submit }}
    </form>
    </div>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}
{% block content %}

    <div class="top">
        <div class="title"><h1>My Hiking Blog</h1></div>
    </div>
    {% for post in posts|reverse: %}
    <div class="content">
        <div class="card">
            <h2>{{post.title}}</h2>
            <p>{{post.subtitle}}</p>
            <p>Difficulty: {{post.difficulty}} Duration: {{post.length}}</p>
            <a href="{{ url_for('views.get_blog', index=post.id) }}">Read</a>
            {% if current_user.id == 1%}
            <a href="{{ url_for('views.edit_blog', index=post.id) }}">Edit</a>
            <a href="{{ url_for('views.delete_blog', index=post.id) }}">Delete</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="top">
        <div class="title"><h1>Log In</h1></div>
</div>
<div class="card">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('auth.login') }}" novalidate>
        {{ form.csrf_token }}
        <p>{{ form.email.label }} {{ form.email(size=20) }}
            {% for err in form.email.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>

        <p>{{ form.password.label }} {{ form.password(size=30) }}
            {% for err in form.password.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        {{ form.submit }}
    </form>
</div>
{% endblock %}

website/templates/post.html
{% extends "base.html" %}
{% block content %}
<div class="top">
    <div class="title"><h1>{{title}}</h1></div>
</div>
<div class="content">
    <div class="card">
        <h1> {{ post.title }}</h1>
        <h2> {{ post.subtitle }}</h2>
        <h2>Difficulty: {{post.difficulty}} Duration: {{post.length}}</h2>
        <p> {{ post.body }}</p>
    </div>
</div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block content %}
    <div class="top">
        <div class="title"><h1>Sign Up</h1></div>
    </div>
<div class="card">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }} If you have account, go to <a href="{{ url_for('auth.login') }}">login page</a>.
    </div>
    {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('auth.sign_up') }}" novalidate>
        {{ form.csrf_token }}
        <p>{{ form.name.label }} {{ form.name(size=20) }}
            {% for err in form.name.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>{{ form.email.label }} {{ form.email(size=20) }}
            {% for err in form.email.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        <p>{{ form.password.label }} {{ form.password(size=30) }}
            {% for err in form.password.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
                <p>{{ form.confirm_pass.label }} {{ form.confirm_pass(size=30) }}
            {% for err in form.confirm_pass.errors %}
            <span style="color: red">{{ err }}</span>
            {% endfor %}
        </p>
        {{ form.submit }}
    </form>
</div>
{% endblock %}